connector:
    name: oro_importexport
    jobs:
        mailchimp_campaign_import:
            title: orocrm.mailchimp.connector.campaign.job
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_mailchimp.connector.campaign
                        processor: orocrm_mailchimp.importexport.processor.campaign
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 25
                remove:
                    title: remove
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_mailchimp.importexport.reader.processed_entities
                        processor: orocrm_mailchimp.importexport.processor.campaign.remove
                        writer:    orocrm_mailchimp.importexport.writer.campaign.remove

        mailchimp_template_import:
            title: orocrm.mailchimp.connector.template.job
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_mailchimp.connector.template
                        processor: orocrm_mailchimp.importexport.processor.template
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 25
                remove:
                    title: remove
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_mailchimp.importexport.reader.processed_entities
                        processor: orocrm_mailchimp.importexport.processor.template.remove
                        writer:    orocrm_mailchimp.importexport.writer.template.remove

        mailchimp_list_import:
            title: orocrm.mailchimp.connector.list.job
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_mailchimp.connector.list
                        processor: orocrm_mailchimp.importexport.processor.list
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 25
                remove:
                    title: remove
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_mailchimp.importexport.reader.processed_entities
                        processor: orocrm_mailchimp.importexport.processor.list.remove
                        writer:    orocrm_mailchimp.importexport.writer.list.remove

        mailchimp_member_import:
            title: orocrm.mailchimp.connector.member.job
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_mailchimp.connector.member
                        processor: orocrm_mailchimp.importexport.processor.member
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 25

        mailchimp_static_segment_import:
            title: orocrm.mailchimp.connector.static_segment.job
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_mailchimp.connector.static_segment
                        processor: orocrm_mailchimp.importexport.processor.static_segment
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 25

        mailchimp_marketing_list_subscribe:
            title: orocrm.mailchimp.job.mailchimp_marketing_list_subscribe
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_mailchimp.importexport.reader.marketing_list_subscribe
                        processor: orocrm_mailchimp.importexport.processor.members_sync
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 25

        mailchimp_static_segment_member_add_state:
            title: orocrm.mailchimp.job.static_segment_member_add_state
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_mailchimp.importexport.reader.static_segment_member_add_state
                        processor: orocrm_mailchimp.importexport.processor.static_segment_member_add_state
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 25

        mailchimp_static_segment_member_remove_state:
            title: orocrm.mailchimp.job.static_segment_member_add_state
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_mailchimp.importexport.reader.static_segment_member_remove_state
                        processor: orocrm_mailchimp.importexport.processor.static_segment_member_remove_state
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 25
