datagrid:
    orocrm-mailchimp-member-grid:
        extended_entity_name: OroCRM\Bundle\MailChimpBundle\Entity\Member
        source:
            type: orm
            query:
                select:
                    - m.id
                    - m.firstName
                    - m.lastName
                    - m.email
                    - m.memberRating
                    - m.lastChangedAt
                from:
                    - { table: OroCRM\Bundle\MailChimpBundle\Entity\Member, alias: m }
        columns:
            email:
                label: orocrm.mailchimp.member.email.label
            firstName:
                label: orocrm.mailchimp.member.first_name.label
            lastName:
                label: orocrm.mailchimp.member.last_name.label
            memberRating:
                label: orocrm.mailchimp.member.member_rating.label
            lastChangedAt:
                label: orocrm.mailchimp.member.last_changed_at.label
                frontend_type: datetime
        filters:
            columns:
                email:
                    type:       string
                    data_name:  m.email
                firstName:
                    type:       string
                    data_name:  m.firstName
                lastName:
                    type:       string
                    data_name:  m.lastName
                memberRating:
                    type:       number
                    data_name:  m.memberRating
                lastChangedAt:
                    type:       datetime
                    data_name:  m.lastChangedAt
        sorters:
            columns:
                email:         { data_name: m.email }
                firstName:     { data_name: m.firstName }
                lastName:      { data_name: m.lastName }
                memberRating:  { data_name: m.memberRating }
                lastChangedAt: { data_name: m.lastChangedAt }
        properties:
            id: ~
#            view_link:
#                type: url
#                route: orocrm_marketing_list_view
#                params: [ id ]
#        actions:
#            view:
#                type:         navigate
#                label:        oro.grid.action.view
#                link:         view_link
#                icon:         eye-open
#                acl_recource: orocrm_marketing_list_view
#                rowAction:    true
#
