placeholders:
    view_sync_status_data:
        items:
            orocrm_mailchimp_sync_data: ~
    view_sync_status_badge:
        items:
            orocrm_mailchimp_sync_badge: ~

items:
    orocrm_mailchimp_sync_data:
        action: OroCRMMailChimpBundle:MailChimp:emailCampaignSyncStatus
        applicable: @orocrm_mailchimp.placeholder.filter->isApplicableOnMarketingList($entity$)
    orocrm_mailchimp_sync_badge:
        action: OroCRMMailChimpBundle:MailChimp:emailCampaignSyncStatusBadge
        applicable: @orocrm_mailchimp.placeholder.filter->isApplicableOnMarketingList($entity$)
