placeholders:
    view_navButtons_before:
        items:
            orocrm_mailchimp_marketing_list_buttons: ~
    view_content_data_email_campaign_status_positive:
        items:
            orocrm_mailchimp_emailcampaign_stats_positive: ~
    view_content_data_email_campaign_status_negative:
        items:
            orocrm_mailchimp_emailcampaign_stats_negative: ~

items:
    orocrm_mailchimp_marketing_list_buttons:
        action: OroCRMMailChimpBundle:MailChimp:connectionButtons
        applicable: @orocrm_mailchimp.placeholder.filter.buttons_filder->isApplicable($entity$)
    orocrm_mailchimp_emailcampaign_stats_positive:
        action: OroCRMMailChimpBundle:MailChimp:emailCampaignStatsPositive
        applicable: @orocrm_mailchimp.placeholder.filter.email_campaign->isApplicableOnEmailCampaign($entity$)
    orocrm_mailchimp_emailcampaign_stats_negative:
        action: OroCRMMailChimpBundle:MailChimp:emailCampaignStatsNegative
        applicable: @orocrm_mailchimp.placeholder.filter.email_campaign->isApplicableOnEmailCampaign($entity$)
