placeholders:
    view_content_data_additional_information:
        items:
            orocrm_mailchimp_sync: ~

items:
    orocrm_mailchimp_sync:
        template: OroCRMMailChimpBundle:Placeholder:syncStatus.html.twig
        applicable: @orocrm_mailchimp.placeholder.filter->isApplicable($entity$)
