placeholders:
    view_content_data_email_campaign_status:
        items:
            orocrm_mailchimp_emailcampaign_stats: ~

items:
    orocrm_mailchimp_emailcampaign_stats:
        action: OroCRMMailChimpBundle:MailChimp:emailCampaignStats
        applicable: @orocrm_mailchimp.placeholder.filter->isApplicableOnEmailCampaign($entity$)
