placeholders:
    view_navButtons_before:
        items:
            orocrm_mailchimp_marketing_list_buttons: ~
    marketing_list_sync_info:
        items:
            orocrm_mailchimp_marketing_list_sync_data: ~

items:
    orocrm_mailchimp_marketing_list_buttons:
        action: OroCRMMailChimpBundle:MailChimp:connectionButtons
        applicable: @orocrm_mailchimp.placeholder.filter.buttons_filder->isApplicable($entity$)
    orocrm_mailchimp_marketing_list_sync_data:
        action: OroCRMMailChimpBundle:MailChimp:marketingListSyncStatus
        applicable: @orocrm_mailchimp.placeholder.filter.sync_status->isApplicableOnMarketingList($marketingList$)
