placeholders:
    view_sync_status_data:
        items:
            orocrm_mailchimp_sync_data: ~
    view_sync_status_badge:
        items:
            orocrm_mailchimp_sync_badge: ~

items:
    orocrm_mailchimp_sync_data:
        template: OroCRMMailChimpBundle:Placeholder:syncStatus.html.twig
        applicable: @orocrm_mailchimp.placeholder.filter->isApplicableOnMarketingList($entity$)
    orocrm_mailchimp_sync_badge:
        template: OroCRMMailChimpBundle:Placeholder:syncStatusBadge.html.twig
        applicable: @orocrm_mailchimp.placeholder.filter->isApplicableOnMarketingList($entity$)
