definitions:
    synchronize_marketing_list_item_for_mailchimp_member_activity:
        label:   'Synchronizes OroCRM Marketing List Item for MailChimp Member Activity'
        enabled: true
        entity:  OroCRM\Bundle\MailChimpBundle\Entity\MemberActivity
        exclude_definitions: [synchronize_marketing_list_item_for_mailchimp_member_activity]
        actions_configuration:
            - @tree:
                conditions:
                    @not_empty: $member.subscribersList.marketingList
                actions:
                    - @create_entity: # create OroCRM Marketing List Item
                        conditions: # if OroCRM Marketing List Item not exists
                            @empty: $marketingListItem
                        parameters:
                            class:     OroCRM\Bundle\MarketingListBundle\Entity\MarketingListItem
                            attribute: $marketingListItem
                            data:
                                entityId:       $id
                                marketingList:  $subscribersList.marketingList
                                contactedTimes: 0
                                lastContactedAt: $.lastContactedAt

    create_email_campaign_for_mailchimp_campaign:
        label:   Create Email Campaign for MailChimp Campaign
        enabled: true
        entity:  OroCRM\Bundle\MailChimpBundle\Entity\Campaign
        exclude_definitions: [create_email_campaign_for_mailchimp_campaign]
        actions_configuration:
            - @tree:
                actions:
                    # Prepare constants values
                    - @assign_constant_value:
                        attribute: $.statusSent
                        value: OroCRM\Bundle\MailChimpBundle\Entity\Campaign::STATUS_SENT
                    - @assign_constant_value:
                        attribute: $.scheduleManual
                        value: OroCRM\Bundle\CampaignBundle\Entity\EmailCampaign::SCHEDULE_MANUAL
                    - @assign_constant_value:
                        attribute: $.mailchimpTransport
                        value: OroCRM\Bundle\MailChimpBundle\Transport\MailChimpTransport::NAME
                    # Create OroCRM EmailCampaign
                    - @tree:
                        # If OroCRM EmailCampaign not exists and
                        # MailChimp Campaign relates to OroCRM MarketingList and
                        # MailChimp Campaign has "sent" status
                        conditions:
                            @and:
                                - @empty: $emailCampaign
                                - @not_empty: $staticSegment
                                - @not_empty: $staticSegment.marketingList
                                - @equal: [$status, 'sent']
                        actions:
                            - @create_entity: # Create OroCRM EmailCampaign
                                class:     OroCRM\Bundle\CampaignBundle\Entity\EmailCampaign
                                attribute: $emailCampaign
                                data:
                                    name: $title
                                    schedule: $.scheduleManual
                                    sent: true
                                    sentAt: $sendTime
                                    senderEmail: $fromEmail
                                    senderName: $fromName
                                    transport: $.mailchimpTransport
                                    owner: $channel.defaultUserOwner
                                    organization: $channel.defaultUserOwner.organization
                            - @create_entity: # Create MailChimpTransportSettings
                                class:     OroCRM\Bundle\MailChimpBundle\Entity\MailChimpTransportSettings
                                attribute: $emailCampaign.transportSettings
                                data:
                                    channel: $channel
                                    template: $template
triggers:
    synchronize_marketing_list_item_for_mailchimp_member_activity:
        -
            event:    create
            queued:   true

    create_email_campaign_for_mailchimp_campaign:
        -
            event:    create
            queued:   true
