parameters:
    # Entities
    orocrm_mailchimp.entity.campaign.class: OroCRM\Bundle\MailChimpBundle\Entity\MailChimpCampaign
    orocrm_mailchimp.entity.template.class: OroCRM\Bundle\MailChimpBundle\Entity\Template

    orocrm_mailchimp.client.factory.class: OroCRM\Bundle\MailChimpBundle\Model\MailChimpClientFactory

    #Serializers
    orocrm_mailchimp.importexport.serializer.datetime.class: OroCRM\Bundle\MailChimpBundle\ImportExport\Serializer\DateTimeSerializer

    #Processors
    orocrm_mailchimp.importexport.processor.import_abstract.class: OroCRM\Bundle\MailChimpBundle\ImportExport\Processor\IntegrationImportProcessor

    # Forms and extensions
    orocrm_mailchimp.form.type.integration_transport_settings.class: OroCRM\Bundle\MailChimpBundle\Form\Type\IntegrationSettingsType
    orocrm_mailchimp.form.type.api_key_type.class: OroCRM\Bundle\MailChimpBundle\Form\Type\ApiKeyType

    # Integration related services
    orocrm_mailchimp.transport.integration_transport.class: OroCRM\Bundle\MailChimpBundle\Provider\MailChimpTransport
    orocrm_mailchimp.provider.channel_type.class: OroCRM\Bundle\MailChimpBundle\Provider\ChannelType

    # Connectors
    orocrm_mailchimp.connector.campaign.class: OroCRM\Bundle\MailChimpBundle\Provider\CampaignConnector
    orocrm_mailchimp.connector.template.class: OroCRM\Bundle\MailChimpBundle\Provider\TemplateConnector

    # Data Converter
    orocrm_mailchimp.importexport.data_converter.campaign.class: OroCRM\Bundle\MailChimpBundle\ImportExport\DataConverter\CampaignDataConverter
    orocrm_mailchimp.importexport.data_converter.template.class: OroCRM\Bundle\MailChimpBundle\ImportExport\DataConverter\TemplateDataConverter

services:
    orocrm_mailchimp.client.factory:
        class: %orocrm_mailchimp.client.factory.class%

    #Serializers
    orocrm_mailchimp.importexport.serializer.datetime:
        class: %orocrm_mailchimp.importexport.serializer.datetime.class%
        tags:
            - { name: oro_importexport.normalizer }

    # Forms and extensions
    orocrm_mailchimp.form.type.api_key_type:
        class: %orocrm_mailchimp.form.type.api_key_type.class%
        tags:
            - { name: form.type, alias: "orocrm_mailchimp_api_key_type" }

    orocrm_mailchimp.form.type.integration_transport_settings:
        class: %orocrm_mailchimp.form.type.integration_transport_settings.class%
        tags:
            - { name: form.type, alias: "orocrm_mailchimp_integration_transport_setting_type" }

    # Integration related services
    orocrm_mailchimp.provider.channel_type:
            class: %orocrm_mailchimp.provider.channel_type.class%
            tags:
                - { name: oro_integration.channel, type: mailchimp }

    orocrm_mailchimp.transport.integration_transport:
        class: %orocrm_mailchimp.transport.integration_transport.class%
        arguments:
            - @orocrm_mailchimp.client.factory
        tags:
            - { name: oro_integration.transport, type: mailchimp_api, channel_type: mailchimp }

    # Connectors
    orocrm_mailchimp.connector.campaign:
        class: %orocrm_mailchimp.connector.campaign.class%
        arguments:
            - @oro_importexport.context_registry
            - @oro_integration.logger.strategy
            - @oro_integration.provider.connector_context_mediator
        calls:
            - [setEntityName, [%orocrm_mailchimp.entity.campaign.class%]]
        tags:
            - { name: oro_integration.connector, type: campaign, channel_type: mailchimp }

    orocrm_mailchimp.connector.template:
        class: %orocrm_mailchimp.connector.template.class%
        arguments:
            - @oro_importexport.context_registry
            - @oro_integration.logger.strategy
            - @oro_integration.provider.connector_context_mediator
        calls:
            - [setEntityName, [%orocrm_mailchimp.entity.template.class%]]
        tags:
            - { name: oro_integration.connector, type: template, channel_type: mailchimp }

    # Data Converter
    orocrm_mailchimp.importexport.data_converter.campaign:
        class: %orocrm_mailchimp.importexport.data_converter.campaign.class%
        parent: oro_importexport.data_converter.configurable

    orocrm_mailchimp.importexport.data_converter.template:
        class: %orocrm_mailchimp.importexport.data_converter.template.class%
        parent: oro_importexport.data_converter.configurable

    # Strategy
    orocrm_mailchimp.importexport.strategy.template.add_or_replace:
        parent: oro_importexport.strategy.configurable_add_or_replace

    # Import
    orocrm_mailchimp.importexport.processor.campaign:
        parent: oro_importexport.processor.import_abstract
        calls:
            - [setDataConverter, [@orocrm_mailchimp.importexport.data_converter.campaign]]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %orocrm_mailchimp.entity.campaign.class%, alias: orocrm_mailchimp.processor.campaign }

    orocrm_mailchimp.importexport.processor.template:
            class: %orocrm_mailchimp.importexport.processor.import_abstract.class%
            parent: oro_importexport.processor.import_abstract
            calls:
                - [setDataConverter, [@orocrm_mailchimp.importexport.data_converter.template]]
                - [setStrategy, [@orocrm_mailchimp.importexport.strategy.template.add_or_replace]]
            tags:
                - { name: oro_importexport.processor, type: import, entity: %orocrm_mailchimp.entity.template.class%, alias: orocrm_mailchimp.processor.template }
