parameters:
    # Entities
    orocrm_mailchimp.entity.campaign.class: OroCRM\Bundle\MailChimpBundle\Entity\Campaign
    orocrm_mailchimp.entity.template.class: OroCRM\Bundle\MailChimpBundle\Entity\Template
    orocrm_mailchimp.entity.subscribers_list.class: OroCRM\Bundle\MailChimpBundle\Entity\SubscribersList

    # Forms and extensions
    orocrm_mailchimp.form.type.integration_transport_settings.class: OroCRM\Bundle\MailChimpBundle\Form\Type\IntegrationSettingsType
    orocrm_mailchimp.form.type.api_key_type.class: OroCRM\Bundle\MailChimpBundle\Form\Type\ApiKeyType

    # Integration related services
    orocrm_mailchimp.transport.integration_transport.class: OroCRM\Bundle\MailChimpBundle\Provider\Transport\MailChimpTransport
    orocrm_mailchimp.provider.channel_type.class: OroCRM\Bundle\MailChimpBundle\Provider\ChannelType
    orocrm_mailchimp.client.class: OroCRM\Bundle\MailChimpBundle\Provider\Transport\MailChimpClient
    orocrm_mailchimp.client.factory.class: OroCRM\Bundle\MailChimpBundle\Provider\Transport\MailChimpClientFactory

    # Readers
    orocrm_mailchimp.importexport.reader.processed_entities.class:  OroCRM\Bundle\MailChimpBundle\ImportExport\Reader\ProcessedEntities

    # Writers
    orocrm_mailchimp.importexport.writer.remove.class: OroCRM\Bundle\MailChimpBundle\ImportExport\Writer\RemoveWriter

    #Serializers
    orocrm_mailchimp.importexport.serializer.datetime.class: OroCRM\Bundle\MailChimpBundle\ImportExport\Serializer\DateTimeSerializer

    # Strategies
    orocrm_mailchimp.importexport.strategy.campaign.class: OroCRM\Bundle\MailChimpBundle\ImportExport\Strategy\CampaignImportStrategy
    orocrm_mailchimp.importexport.strategy.template.class: OroCRM\Bundle\MailChimpBundle\ImportExport\Strategy\TemplateImportStrategy
    orocrm_mailchimp.importexport.strategy.list.class: OroCRM\Bundle\MailChimpBundle\ImportExport\Strategy\ListImportStrategy

    # Connectors
    orocrm_mailchimp.connector.template.class: OroCRM\Bundle\MailChimpBundle\Provider\TemplateConnector
    orocrm_mailchimp.connector.list.class: OroCRM\Bundle\MailChimpBundle\Provider\ListConnector
    orocrm_mailchimp.connector.campaign.class: OroCRM\Bundle\MailChimpBundle\Provider\CampaignConnector

    # Data Converter
    orocrm_mailchimp.importexport.data_converter.template.class: OroCRM\Bundle\MailChimpBundle\ImportExport\DataConverter\TemplateDataConverter
    orocrm_mailchimp.importexport.data_converter.list.class: OroCRM\Bundle\MailChimpBundle\ImportExport\DataConverter\ListDataConverter
    orocrm_mailchimp.importexport.data_converter.campaign.class: OroCRM\Bundle\MailChimpBundle\ImportExport\DataConverter\CampaignDataConverter

    # Processors
    orocrm_mailchimp.importexport.processor.import.class: OroCRM\Bundle\MailChimpBundle\ImportExport\Processor\ImportProcessor
    orocrm_mailchimp.importexport.processor.remove.class: OroCRM\Bundle\MailChimpBundle\ImportExport\Processor\RemoveProcessor

services:
    orocrm_mailchimp.client.factory:
        class: %orocrm_mailchimp.client.factory.class%
        arguments:
            - %orocrm_mailchimp.client.class%

    # Readers
    orocrm_mailchimp.importexport.reader.processed_entities:
        class: %orocrm_mailchimp.importexport.reader.processed_entities.class%
        arguments:
            - @oro_importexport.context_registry

    # Writers
    orocrm_mailchimp.importexport.writer.template.remove:
        class: %orocrm_mailchimp.importexport.writer.remove.class%
        arguments:
            - @doctrine
            - %orocrm_mailchimp.entity.template.class%
            - 'originId'

    orocrm_mailchimp.importexport.writer.list.remove:
        class: %orocrm_mailchimp.importexport.writer.remove.class%
        arguments:
            - @doctrine
            - %orocrm_mailchimp.entity.subscribers_list.class%
            - 'originId'

    orocrm_mailchimp.importexport.writer.campaign.remove:
        class: %orocrm_mailchimp.importexport.writer.remove.class%
        arguments:
            - @doctrine
            - %orocrm_mailchimp.entity.campaign.class%
            - 'originId'

    #Serializers
    orocrm_mailchimp.importexport.serializer.datetime:
        class: %orocrm_mailchimp.importexport.serializer.datetime.class%
        tags:
            - { name: oro_importexport.normalizer }

    # Forms and extensions
    orocrm_mailchimp.form.type.api_key_type:
        class: %orocrm_mailchimp.form.type.api_key_type.class%
        tags:
            - { name: form.type, alias: "orocrm_mailchimp_api_key_type" }

    orocrm_mailchimp.form.type.integration_transport_settings:
        class: %orocrm_mailchimp.form.type.integration_transport_settings.class%
        tags:
            - { name: form.type, alias: "orocrm_mailchimp_integration_transport_setting_type" }

    # Integration related services
    orocrm_mailchimp.provider.channel_type:
            class: %orocrm_mailchimp.provider.channel_type.class%
            tags:
                - { name: oro_integration.channel, type: mailchimp }

    orocrm_mailchimp.transport.integration_transport:
        class: %orocrm_mailchimp.transport.integration_transport.class%
        arguments:
            - @orocrm_mailchimp.client.factory
            - @doctrine
        tags:
            - { name: oro_integration.transport, type: mailchimp_api, channel_type: mailchimp }

    # Connectors
    orocrm_mailchimp.connector.abstract:
        abstract: true
        arguments:
            - @oro_importexport.context_registry
            - @oro_integration.logger.strategy
            - @oro_integration.provider.connector_context_mediator
        calls:
            - [setManagerRegistry, [@doctrine]]

    orocrm_mailchimp.connector.template:
        class: %orocrm_mailchimp.connector.template.class%
        parent: orocrm_mailchimp.connector.abstract
        calls:
            - [setEntityName, [%orocrm_mailchimp.entity.template.class%]]
        tags:
            - { name: oro_integration.connector, type: template, channel_type: mailchimp }

    orocrm_mailchimp.connector.list:
        class: %orocrm_mailchimp.connector.list.class%
        parent: orocrm_mailchimp.connector.abstract
        calls:
            - [setEntityName, [%orocrm_mailchimp.entity.subscribers_list.class%]]
        tags:
            - { name: oro_integration.connector, type: list, channel_type: mailchimp }

    orocrm_mailchimp.connector.campaign:
        class: %orocrm_mailchimp.connector.campaign.class%
        parent: orocrm_mailchimp.connector.abstract
        calls:
            - [setEntityName, [%orocrm_mailchimp.entity.campaign.class%]]
        tags:
            - { name: oro_integration.connector, type: campaign, channel_type: mailchimp }

    # Data Converter
    orocrm_mailchimp.importexport.data_converter.campaign:
        class: %orocrm_mailchimp.importexport.data_converter.campaign.class%

    orocrm_mailchimp.importexport.data_converter.template:
        class: %orocrm_mailchimp.importexport.data_converter.template.class%

    orocrm_mailchimp.importexport.data_converter.list:
        class: %orocrm_mailchimp.importexport.data_converter.list.class%

    # Strategy
    orocrm_mailchimp.importexport.strategy.template.add_or_replace:
        class: %orocrm_mailchimp.importexport.strategy.template.class%
        parent: oro_importexport.strategy.configurable_add_or_replace
        calls:
            - [setLogger, [@oro_integration.logger.strategy]]

    orocrm_mailchimp.importexport.strategy.list:
        class: %orocrm_mailchimp.importexport.strategy.list.class%
        parent: oro_importexport.strategy.configurable_add_or_replace
        calls:
            - [setOwnerHelper, [@oro_integration.helper.default_owner_helper]]
            - [setLogger, [@oro_integration.logger.strategy]]

    orocrm_mailchimp.importexport.strategy.campaign:
        class: %orocrm_mailchimp.importexport.strategy.campaign.class%
        parent: oro_importexport.strategy.configurable_add_or_replace
        calls:
            - [setOwnerHelper, [@oro_integration.helper.default_owner_helper]]
            - [setLogger, [@oro_integration.logger.strategy]]

    # Processors
    orocrm_mailchimp.importexport.processor.import_abstract:
        parent: oro_importexport.processor.import_abstract
        abstract: true
        calls:
            - [setContextRegistry, [@oro_importexport.context_registry]]

    orocrm_mailchimp.importexport.processor.campaign:
        class: %orocrm_mailchimp.importexport.processor.import.class%
        parent: orocrm_mailchimp.importexport.processor.import_abstract
        calls:
            - [setDataConverter, [@orocrm_mailchimp.importexport.data_converter.campaign]]
            - [setStrategy, [@orocrm_mailchimp.importexport.strategy.campaign]]
            - [setEntityName, [%orocrm_mailchimp.entity.campaign.class%]]

    orocrm_mailchimp.importexport.processor.list:
        class: %orocrm_mailchimp.importexport.processor.import.class%
        parent: orocrm_mailchimp.importexport.processor.import_abstract
        calls:
            - [setDataConverter, [@orocrm_mailchimp.importexport.data_converter.list]]
            - [setStrategy, [@orocrm_mailchimp.importexport.strategy.list]]
            - [setEntityName, [%orocrm_mailchimp.entity.subscribers_list.class%]]

    orocrm_mailchimp.importexport.processor.template:
        class: %orocrm_mailchimp.importexport.processor.import.class%
        parent: orocrm_mailchimp.importexport.processor.import_abstract
        calls:
            - [setDataConverter, [@orocrm_mailchimp.importexport.data_converter.template]]
            - [setStrategy, [@orocrm_mailchimp.importexport.strategy.template.add_or_replace]]
            - [setEntityName, [%orocrm_mailchimp.entity.template.class%]]

    orocrm_mailchimp.importexport.processor.remove.abstract:
        class: %orocrm_mailchimp.importexport.processor.remove.class%
        abstract: true
        arguments:
            - @oro_importexport.context_registry
            - @oro_entity.doctrine_helper

    orocrm_mailchimp.importexport.processor.template.remove:
        parent: orocrm_mailchimp.importexport.processor.remove.abstract
        calls:
            - [setEntityName, [%orocrm_mailchimp.entity.template.class%]]
            - [setSearchField, ['originId']]

    orocrm_mailchimp.importexport.processor.list.remove:
        parent: orocrm_mailchimp.importexport.processor.remove.abstract
        calls:
            - [setEntityName, [%orocrm_mailchimp.entity.subscribers_list.class%]]
            - [setSearchField, ['originId']]

    orocrm_mailchimp.importexport.processor.campaign.remove:
        parent: orocrm_mailchimp.importexport.processor.remove.abstract
        calls:
            - [setEntityName, [%orocrm_mailchimp.entity.campaign.class%]]
            - [setSearchField, ['originId']]
