OroCRM\Bundle\MailChimpBundle\Entity\MailChimpTransport:
    properties:
        apiKey:
            - NotBlank: ~
            - Length:
                min: 32

OroCRM\Bundle\MailChimpBundle\Entity\MailChimpTransportSettings:
    properties:
        channel:
            - NotBlank: ~
        template:
            - NotBlank: ~
