OroCRM\Bundle\MailChimpBundle\Entity\MailChimpTransport:
    properties:
        apiKey:
            - NotBlank: ~
            - Length:
                min: 32

OroCRM\Bundle\MailChimpBundle\Entity\MailChimpTransportSettings:
    properties:
        channel:
            - NotBlank: ~
        template:
            - NotBlank: ~

OroCRM\Bundle\MarketingListBundle\Entity\MarketingList:
    constraints:
        - OroCRM\Bundle\MailChimpBundle\Validator\Constraints\EmailColumnConstraint: ~
