workflows:
    mailchimp_marketing_list_connect_flow:
        steps:
            connected:
                label: 'MailChimp Connected'
                allowed_transitions:
                    - refresh
