workflows:
    mailchimp_marketing_list_connect_flow:
        transition_definitions:
            connect_definition:
                pre_conditions: # applicable only for marketing lists with email fields when at least one mailchimp integration is active
                    @and:
                        - @has_active_integration: 'mailchimp'
                        - @has_contact_information:
                            marketing_list: $marketing_list
                            type: 'email'
                conditions:
                    @and:
                        - @not_empty:
                            message: 'MailChimp integration must be selected'
                            parameters: $mailchimp_integration
                        - @not_empty:
                            message: 'MailChimp List must be selected'
                            parameters: $mailchimp_list
                post_actions: # create StaticSegment and schedule segment sync
                    - @create_entity:
                        class: OroCRM\Bundle\MailChimpBundle\Entity\StaticSegment
                        attribute: $static_segment
                        flush: true
                        data:
                            name:            $segment_name
                            marketingList:   $marketing_list
                            channel:         $mailchimp_integration
                            subscribersList: $mailchimp_list
                            syncStatus:      'not_synced'
                    - @format_string:
                        attribute: $.result.segmentArguments
                        string: '--segments=%segment_id%'
                        arguments:
                            segment_id: $static_segment.id
                    - @create_entity:
                        class: JMS\JobQueueBundle\Entity\Job
                        attribute: $.result.syncJob
                        flush: true
                        arguments:
                            - 'oro:cron:mailchimp:sync-segment'
                            - [$.result.segmentArguments]
            refresh_definition:
                conditions: # allow refresh of marketing list with email fields for active integration when segment is synced
                    @and:
                        - @not_empty: $static_segment
                        - @equal: [$static_segment.syncStatus, 'synced']
                        - @equal: [$static_segment.channel.enabled, true]
                        - @has_contact_information:
                            marketing_list: $marketing_list
                            type: 'email'
                post_actions: #schedule segment sync
                    - @format_string:
                        attribute: $.result.segmentArguments
                        string: '--segments=%segment_id%'
                        arguments:
                            segment_id: $static_segment.id
                    - @create_entity:
                        class: JMS\JobQueueBundle\Entity\Job
                        attribute: $.result.syncJob
                        flush: true
                        arguments:
                            - 'oro:cron:mailchimp:sync-segment'
                            - [$.result.segmentArguments]
