workflows:
    mailchimp_marketing_list_connect_flow:
        transitions:
            __start__:
                label: 'Connect to MailChimp'
                step_to: connected
                is_start: true
                is_hidden: false
                is_unavailable_hidden: true
                transition_definition: connect_definition
                frontend_options:
                    icon: 'icon-exchange'
                    class: 'btn-primary'
                form_options:
                    attribute_fields:
                        segment_name:
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                                    - Length:
                                        max: 100
                                        maxMessage: "Segment name cannot be longer than {{ limit }} characters long"
                        mailchimp_integration:
                            form_type: 'orocrm_mailchimp_integration_select'
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        mailchimp_list:
                            form_type: 'orocrm_mailchimp_list_select'
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                                channel_field: 'mailchimp_integration'
                    attribute_default_values:
                        segment_name: $marketing_list.name
            refresh:
                label: 'Sync to MailChimp'
                step_to: connected
                is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-refresh'
                    class: 'btn-primary'
                transition_definition: refresh_definition
