imports:
    - { resource: 'mailchimp_marketing_list_connect_flow/steps.yml' }
    - { resource: 'mailchimp_marketing_list_connect_flow/attributes.yml' }
    - { resource: 'mailchimp_marketing_list_connect_flow/transitions.yml' }
    - { resource: 'mailchimp_marketing_list_connect_flow/transition_definitions.yml' }

workflows:
    mailchimp_marketing_list_connect_flow:
        label: 'MailChimp Marketing List Connector'
        entity: OroCRM\Bundle\MarketingListBundle\Entity\MarketingList
        entity_attribute: marketing_list
        start_step: connect
        steps_display_ordered: false
