imports:
    - { resource: 'marketing_list/steps.yml' }
    - { resource: 'marketing_list/attributes.yml' }
    - { resource: 'marketing_list/transitions.yml' }
    - { resource: 'marketing_list/transition_definitions.yml' }

workflows:
    marketing_list:
        label: 'MailChimp Marketing List Connector'
        entity: OroCRM\Bundle\MarketingListBundle\Entity\MarketingList
        entity_attribute: marketingList
        start_step: connect
        steps_display_ordered: false
